// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simple_Shop.Data;

namespace Simple_Shop.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20210607150352_IniitialEntity")]
    partial class IniitialEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Simple_Shop.Models.PicPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pic1Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic2Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic3Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic4Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic5Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic6Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PicPaths");
                });

            modelBuilder.Entity("Simple_Shop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PicPath_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PicPath_Id")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Simple_Shop.Models.Product", b =>
                {
                    b.HasOne("Simple_Shop.Models.PicPath", "PicPath")
                        .WithOne("Product")
                        .HasForeignKey("Simple_Shop.Models.Product", "PicPath_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicPath");
                });

            modelBuilder.Entity("Simple_Shop.Models.PicPath", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
